#-- Spring Boot Configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crm
  freemarker:
    template-loader-path: classpath:/
      
server:
  port: 8080
  context-path: /
   
    
#-- Application Configuration
app:
  image:
    path: /home/mr_tranlethanh/crm/images
    size: 8000000
    maxWidth: 1200
    maxHeight: 1200
    location: /home/mr_tranlethanh/crm

  url: crm-client-215407.appspot.com

